"use client";
import {
  ArrowCounterClockwise,
  ArrowDown,
  ArrowLeft,
  ArrowRight,
  ArrowSquareOut,
  ArrowUpRight,
  ArrowsLeftRight,
  Article,
  Bell,
  BookOpenText,
  CalendarBlank,
  Camera,
  CaretDown,
  CaretLeft,
  CaretRight,
  ChartLineUp,
  ChatCircleText,
  Check,
  CheckCircle,
  ClipboardText,
  Clock,
  ClockCounterClockwise,
  Compass,
  CreditCard,
  DotsThree,
  DownloadSimple,
  EnvelopeSimple,
  Eye,
  EyeSlash,
  FileText,
  FilmStrip,
  Flag,
  FunnelSimple,
  Gavel,
  GearSix,
  GlobeSimple,
  HandGrabbing,
  Handshake,
  Heart,
  HourglassMedium,
  House,
  Image,
  Info,
  LinkSimple,
  List,
  LockSimple,
  MagnifyingGlass,
  MapPin,
  MicrophoneStage,
  Minus,
  MusicNotes,
  Package,
  Palette,
  PaperPlaneTilt,
  Pause,
  PenNib,
  PencilSimple,
  PersonSimpleTaiChi,
  Planet,
  Play,
  PlugsConnected,
  Plus,
  Prohibit,
  Receipt,
  Scales,
  SealCheck,
  ShieldCheck,
  ShoppingCartSimple,
  SignOut,
  Sparkle,
  SpinnerGap,
  StarFour,
  Storefront,
  TShirt,
  Tag,
  Ticket,
  Trash,
  UploadSimple,
  UserCheck,
  UserCircle,
  UsersThree,
  VideoCamera,
  Warning,
  WarningCircle,
  X,
  XCircle,
  type Icon as PhosphorIcon,
} from "@phosphor-icons/react";
const icons: Record<string, PhosphorIcon> = {
  "arrow-counter-clockwise": ArrowCounterClockwise,
  "arrow-down": ArrowDown,
  "arrow-left": ArrowLeft,
  "arrow-right": ArrowRight,
  "arrow-square-out": ArrowSquareOut,
  "arrow-up-right": ArrowUpRight,
  "arrows-left-right": ArrowsLeftRight,
  article: Article,
  bell: Bell,
  "book-open-text": BookOpenText,
  "calendar-blank": CalendarBlank,
  camera: Camera,
  "caret-down": CaretDown,
  "caret-left": CaretLeft,
  "caret-right": CaretRight,
  "chart-line-up": ChartLineUp,
  "chat-circle-text": ChatCircleText,
  check: Check,
  "check-circle": CheckCircle,
  "clipboard-text": ClipboardText,
  clock: Clock,
  "clock-counter-clockwise": ClockCounterClockwise,
  compass: Compass,
  "credit-card": CreditCard,
  "dots-three": DotsThree,
  "download-simple": DownloadSimple,
  "envelope-simple": EnvelopeSimple,
  eye: Eye,
  "eye-slash": EyeSlash,
  "file-text": FileText,
  "film-strip": FilmStrip,
  flag: Flag,
  "funnel-simple": FunnelSimple,
  gavel: Gavel,
  "gear-six": GearSix,
  "globe-simple": GlobeSimple,
  "hand-grabbing": HandGrabbing,
  handshake: Handshake,
  heart: Heart,
  "hourglass-medium": HourglassMedium,
  house: House,
  image: Image,
  info: Info,
  "link-simple": LinkSimple,
  list: List,
  "lock-simple": LockSimple,
  "magnifying-glass": MagnifyingGlass,
  "map-pin": MapPin,
  "microphone-stage": MicrophoneStage,
  minus: Minus,
  "music-notes": MusicNotes,
  package: Package,
  palette: Palette,
  "paper-plane-tilt": PaperPlaneTilt,
  pause: Pause,
  "pen-nib": PenNib,
  "pencil-simple": PencilSimple,
  "person-simple-tai-chi": PersonSimpleTaiChi,
  planet: Planet,
  play: Play,
  "plugs-connected": PlugsConnected,
  plus: Plus,
  prohibit: Prohibit,
  receipt: Receipt,
  scales: Scales,
  "seal-check": SealCheck,
  "shield-check": ShieldCheck,
  "shopping-cart-simple": ShoppingCartSimple,
  "sign-out": SignOut,
  sparkle: Sparkle,
  "spinner-gap": SpinnerGap,
  "star-four": StarFour,
  storefront: Storefront,
  "t-shirt": TShirt,
  tag: Tag,
  ticket: Ticket,
  trash: Trash,
  "upload-simple": UploadSimple,
  "user-check": UserCheck,
  "user-circle": UserCircle,
  "users-three": UsersThree,
  "video-camera": VideoCamera,
  warning: Warning,
  "warning-circle": WarningCircle,
  x: X,
  "x-circle": XCircle,
};
export function Icon({
  name,
  size = 20,
  weight = "regular",
  label,
  className = "",
  spin = false,
  ...rest
}: {
  name: string;
  size?: number;
  weight?: "regular" | "fill" | "bold" | "light" | "duotone";
  label?: string;
  className?: string;
  spin?: boolean;
  style?: React.CSSProperties;
  color?: string;
}) {
  const Component = icons[name] || Sparkle;
  return (
    <Component
      size={size}
      weight={weight}
      className={`as-icon ${spin ? "as-icon--spin" : ""} ${className}`}
      aria-hidden={label ? undefined : true}
      aria-label={label}
      role={label ? "img" : undefined}
      {...rest}
    />
  );
}
